docs/AboutUs.md

Hello Sze Kang, please merge thank you

Change AboutUs.md with personal detail

---

src/main/java/ymfc/commands/Command.java

Due to forgetting to create a branch previously, v1.0 PRs was not tracked on cs2113 tp-progress. This PR is to cover that.

Add commands

---

src/main/java/ymfc/YMFC.java
src/main/java/ymfc/commands/AddRecipeCommand.java
src/main/java/ymfc/commands/ByeCommand.java
src/main/java/ymfc/commands/Command.java
src/main/java/ymfc/commands/DeleteCommand.java
src/main/java/ymfc/commands/ListCommand.java
src/main/java/ymfc/recipe/Recipe.java
src/main/java/ymfc/recipelist/RecipeList.java
src/main/java/ymfc/ui/Ui.java
src/test/java/ymfc/DukeTest.java
src/test/java/ymfc/commands/AddRecipeCommandTest.java
src/test/java/ymfc/commands/DeleteCommandTest.java
src/test/java/ymfc/recipe/RecipeTest.java
src/test/java/ymfc/recipelist/RecipeListTest.java
src/test/java/ymfc/ui/UiTest.java

Refactor classes into proper packages

Create JUnits tests for RecipeList class

---

src/test/java/ymfc/DukeTest.java
src/test/java/ymfc/recipelist/RecipeListTest.java

Delete unused import in DukeTest

Fix JUnit test in RecipeListTest

---

build.gradle
src/main/java/ymfc/exception/EmptyListException.java
src/main/java/ymfc/exception/InvalidCommandException.java
src/main/java/ymfc/exception/MissingDescriptionException.java
src/main/java/ymfc/exception/YMFCException.java
src/main/java/ymfc/recipelist/RecipeList.java

Enable assert in build.Gradle
Add assert in RecipeList class

Create exception class

---

.gitignore
src/main/java/ymfc/YMFC.java
src/main/java/ymfc/commands/AddRecipeCommand.java
src/main/java/ymfc/commands/ByeCommand.java
src/main/java/ymfc/commands/Command.java
src/main/java/ymfc/commands/DeleteCommand.java
src/main/java/ymfc/commands/HelpCommand.java
src/main/java/ymfc/commands/ListCommand.java
src/main/java/ymfc/parser/Parser.java
src/main/java/ymfc/recipe/Recipe.java
src/main/java/ymfc/storage/Storage.java
src/main/java/ymfc/ui/Ui.java
src/test/java/ymfc/commands/AddRecipeCommandTest.java
src/test/java/ymfc/commands/DeleteCommandTest.java
src/test/java/ymfc/parser/ParserTest.java
text-ui-test/EXPECTED.TXT

Allow user to save and load recipes locally
Add logging in main

Create storage class

---

src/main/java/ymfc/ui/Ui.java
text-ui-test/runtest.sh

Add assertion in the Ui readCommand method that user input cannot be empty, and continuously re-prompt user for command until a non-empty command is given. Test script updated to run clean each round.

Add defensiveness to user input

---

src/main/java/ymfc/commands/SortCommand.java
src/main/java/ymfc/parser/Parser.java
src/main/java/ymfc/recipelist/RecipeList.java
src/test/java/ymfc/commands/SortCommandTest.java

Allow list to be sorted by name or time

Add sort command

---

src/main/java/ymfc/commands/EditCommand.java
src/main/java/ymfc/parser/Parser.java
src/main/java/ymfc/recipelist/RecipeList.java
src/test/java/ymfc/commands/EditCommandTest.java

Add edit command to app

---

docs/DeveloperGuide.md
src/main/java/ymfc/parser/Parser.java

Refactored some code in getCommand methods. Also added to Developer Guide.

Update code quality in Parser Class

---

src/main/java/ymfc/commands/AddIngredientCommand.java
src/main/java/ymfc/parser/Parser.java
src/main/java/ymfc/recipe/Recipe.java
src/main/java/ymfc/ui/Ui.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

This PR resolves the following issues regarding bugs
#92 and #90

Bug fixes for commands

---

src/main/java/ymfc/YMFC.java
src/main/java/ymfc/commands/FindIngredCommand.java
src/main/java/ymfc/parser/Parser.java
src/main/java/ymfc/storage/Storage.java
src/main/java/ymfc/ui/Ui.java
src/test/java/ymfc/commands/FindIngredCommandTest.java
src/test/java/ymfc/parser/ParserTest.java

- Add unit tests for findI command implemented

Add ability to find ingredients in ingredientList

---

docs/DeveloperGuide.md
src/main/java/ymfc/commands/EditCommand.java
src/main/java/ymfc/list/RecipeList.java
src/main/java/ymfc/recipe/Recipe.java
src/main/java/ymfc/ui/Ui.java
src/test/java/ymfc/recipe/RecipeTest.java
text-ui-test/EXPECTED.TXT

Fixed indentation issues of how recipes are printed, added ui output for edit function, updated developer guide section for ui class, recipe class and recipelist class.

Fix formatting issues, update developer guide

---

src/main/java/ymfc/commands/FindCommand.java
src/main/java/ymfc/commands/FindIngredCommand.java
src/main/java/ymfc/ui/Ui.java

Resolve #113 
Edit: Any suggestions for the message would be appreciate!

bugfix: Custom message for no recipe or ingredient found

---

docs/team/3ccly.md
src/test/java/ymfc/ui/UiTest.java

A very rudimentary skeleton PPP with not much content yet, also editing authorship of the ui test after the file was refactored a while ago.

Create draft PPP

---

docs/DeveloperGuide.md

Fix PDF formatting

---

src/main/java/ymfc/parser/Parser.java

bugfix: Disallow duplicate value in `options` field of `find` command

---

docs/team/sukkaito.md

Made a draft of my PPP using @KSanjith, @3CCLY and provided [example](https://se-education.org/addressbook-level3/team/johndoe.html) structures. 
You can check out the version on my branch: [Link](https://sukkaito.github.io/tp/team/sukkaito.html)

Sukkaito's PPP draft

---

src/main/java/ymfc/YMFC.java
src/main/java/ymfc/storage/Storage.java

bugfix: Show correct logs for missing savefile

---

docs/DeveloperGuide.md
src/main/java/ymfc/recipe/RecommendedRecipe.java

Add to command class part of the DG

Addition to DG

---

docs/team/ksanjith.md
src/main/java/ymfc/commands/AddIngredientCommand.java
src/main/java/ymfc/commands/AddRecipeCommand.java
src/main/java/ymfc/commands/SortIngredientsCommand.java
src/main/java/ymfc/parser/Parser.java
src/main/java/ymfc/ui/Ui.java
src/test/java/ymfc/commands/SortCommandTest.java
src/test/java/ymfc/commands/SortIngredientsCommandTest.java
text-ui-test/EXPECTED.TXT

This PR resolves #85 . It does the following:
- Allow user to sort ingredients by name
- using "sortI" command
- Prevent duplicate named ingredients from being added
- Duplicate check ignores capitalizations for both ingredients and recipes
- e.g. "Apple Soup" and "appLe SOUP" will be counted as duplicate names

Create Sort Ingredients Command

---

src/main/java/ymfc/commands/AddCommand.java
src/main/java/ymfc/commands/ListIngredientCommand.java
src/main/java/ymfc/parser/Parser.java
src/main/java/ymfc/storage/Storage.java
src/test/java/ymfc/commands/AddCommandTest.java
src/test/java/ymfc/commands/EditCommandTest.java
src/test/java/ymfc/commands/ListIngredientCommandTest.java
src/test/java/ymfc/commands/RandomCommandTest.java
src/test/java/ymfc/parser/ParserTest.java

Solves issue #141 
- AddRecipeCommand -> AddCommand
- ListIngredientsCommand -> ListIngredientCommand

Refactor names of classes to follow naming convention

---

src/main/java/ymfc/YMFC.java
src/main/java/ymfc/parser/Parser.java
src/main/java/ymfc/storage/Storage.java

This PR does the following:
- Makes the app create save files for recipes and ingredients immediately upon launch of app if they dont already exist
- Added tab indents to exception messages in the parser for empty lists

Create save files upon launch of app

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/team/ksanjith.md

This PR does the following
- Adds authorship to the DG and UG for KSanjith
- Add hyperlinks to KSanjith's PPP
- Adds a section to the the DG about the Exception Classes (Fix #212 )

Add KSanjith authorship to DG and UG

---

docs/team/ksanjith.md

Add page breaks in PPP

---

docs/team/3ccly.md

Added page break and hyperlinks

Finalise PPP

---

docs/UserGuide.md

Format UG to support PDF printing
